name: flutter_one
description: "A Reddit-style Flutter blog platform."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.10.0

dependencies:
  dio: ^5.9.0
  flutter:
    sdk: flutter
  go_router: ^14.6.2
  http: ^1.6.0
  intl: ^0.19.0
  shared_preferences: ^2.5.3
  file_picker: ^5.3.2
  http_parser: ^4.1.0
  mime: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
