name: server
description: SQLite server for flutter_one app
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.11.0-93.1.beta

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  sqlite3: ^2.4.6
  path: ^1.9.0
  flutter_one:
    path: ../

dev_dependencies:
  test: ^1.24.0
  http: ^1.2.0

